### ISSUE TITLE
unexpected newline in object literal notation, between nested object and simple property

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee#246]
```
var obj = {
    bar: 1,
    nested : {bar: 'str'},
    foo: 2
}
```

produces: 

```
obj =
  bar: 1
  nested:
    bar: "str"

  foo: 2
```
