### ISSUE TITLE
Double scroll on os X

### ISSUE THREAD

**Issue by RsD0p9BK** [js2coffee/js2coffee#340]
Double scroll on os X
http://cl.ly/image/2i170a2Y0W1e

**Comment by pronebird** [comment]
Duplicate of https://github.com/js2coffee/js2coffee-redux/issues/5 which is closed but not solved..

**Comment by pronebird** [comment]
@RsD0p9BK I think it's more appropriate to have it here since redux was merged in master. My comment was more like heads up to @rstacruz

**Comment by rstacruz** [comment]
thanks—thought I fixed this! (if anyone has pointers on how to fix it thatd be great)

**Comment by rstacruz** [comment]
also, is this firefox or chrome or some other browser?

**Comment by RsD0p9BK** [comment]
opera, chrome, firefox, safari - too

```css
.CodeMirror-scroll {
overflow-x: hidden;
overflow-y: scroll;
}

/* or remove it from html =) */
.CodeMirror-overlayscroll-horizontal,
.CodeMirror-overlayscroll-vertical {
display: none !important;
}
```

looks native http://cl.ly/image/241a2Q2u0Z3k

**Comment by pronebird** [comment]
Is this a bug in code mirror or theme that we use? I hardly understand why soft ware scroll bars even exist...

**Comment by rstacruz** [comment]
It's using the `overlay` mode of the `simplescrollbars` addon for codemirror. not sure why it seems okay on their site but not on js2.coffee. — http://codemirror.net/demo/simplescrollbars.html

**Comment by RsD0p9BK** [comment]
```css
.code-box .CodeMirror, .code-box-popup .CodeMirror {
    padding: 0px;
}
```
